import { Footer, Header } from "@/components/ui";
import Providers from "@/providers";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { notFound } from "next/navigation";
import "./styles/globals.css";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = { title: "Create Next App", description: "Generated by create next app" };

type RootLayoutProps = {
  children: React.ReactNode;
  params: { locale: string };
};

const locales = ["en", "tr"];
function RootLayout({ children, params: { locale } }: RootLayoutProps) {
  if (!locales.includes(locale as any)) notFound();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <div className="min-h-screen bg-primary text-secondary">
            <div className="p-5">
              <Header />
              <main>{children}</main>
            </div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}

export default RootLayout;
