import { Footer, Header } from "@/components/ui";
import Providers from "@/providers";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { notFound } from "next/navigation";
import "./styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const locales = ["en", "tr"];

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  if (!locales.includes(locale as any)) notFound();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={inter.className}>
        {/* <div className="flex flex-col min-h-screen ">
          <header
            className="
          header"
            children="Header"
          />
          <main
            className="
          main"
            children="Content"
          />
          <footer
            className="sticky top-full 
          footer"
            children="Footer"
          />
        </div> */}

        <Providers>
          <div className="min-h-screen bg-primary text-secondary">
            <div className="p-5">
              <Header />
              <main>{children}</main>
            </div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
